import { addDocument, updateDocument, deleteDocument, queryDocuments } from '../../services/firestore.js';
import { canWrite, gateWrite, getTenantId } from '../../tenant-context.js';
import { db } from '../../config.js';
import { collection, onSnapshot } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
import { openRecordPayment } from './record-payment-modal.js';

let invoices = [];
let currentPage = 'list';
let pendingDeepLinkId = null;
let pendingFilter = null;
let activeStatusFilter = 'all'; // all | draft | sent | paid | outstanding | void | cancelled | refunded
let activeDateFrom = '';
let activeDateTo = '';
let invoicesUnsub = null;
let invoicesLoadError = null;

// Called by other views (e.g., customer profile) to request that we open a
// specific invoice after navigating to #invoicing.
export function requestInvoice(invoiceId) {
  pendingDeepLinkId = invoiceId;
}

// Called by the dashboard to navigate in with a specific set of filters.
// opts: { status, from, to }
export function requestInvoiceFilter(opts) {
  pendingFilter = opts || null;
}

export function init() {}

export async function render() {
  // Subscribe in real-time so invoices generated by the recurring-billing
  // engine (rent, fees, etc.) appear without a manual refresh.
  if (invoicesUnsub) { try { invoicesUnsub(); } catch {} invoicesUnsub = null; }
  invoicesLoadError = null;

  const tenantId = getTenantId();
  if (!tenantId) {
    invoices = [];
    renderList();
    return;
  }

  // Prime the list once so the initial render shows something even before
  // onSnapshot delivers. Fire-and-forget.
  queryDocuments('invoices_crm', 'createdAt', 'desc')
    .then(list => {
      invoices = list;
      invoicesLoadError = null;
      if (pendingDeepLinkId) {
        const id = pendingDeepLinkId;
        pendingDeepLinkId = null;
        const inv = invoices.find(i => i.id === id);
        if (inv) { showDetail(inv); return; }
      }
      if (pendingFilter) {
        const f = pendingFilter; pendingFilter = null;
        activeStatusFilter = f.status || 'all';
        activeDateFrom = f.from || '';
        activeDateTo = f.to || '';
      }
      if (currentPage === 'list') renderList();
    })
    .catch(err => { console.error(err); invoices = []; invoicesLoadError = err.code || err.message; renderList(); });

  // Live subscription — re-renders list whenever invoices_crm changes.
  try {
    invoicesUnsub = onSnapshot(
      collection(db, 'tenants', tenantId, 'invoices_crm'),
      (snap) => {
        invoices = snap.docs.map(d => ({ id: d.id, ...d.data() }));
        // Client-sort by createdAt desc (unordered query avoids needing index).
        invoices.sort((a, b) => {
          const ta = a.createdAt?.toDate?.()?.getTime() || 0;
          const tb = b.createdAt?.toDate?.()?.getTime() || 0;
          return tb - ta;
        });
        invoicesLoadError = null;
        if (currentPage === 'list') renderList();
      },
      (err) => {
        console.error('[invoicing] subscription error:', err);
        invoicesLoadError = err.code || err.message;
        if (currentPage === 'list') renderList();
      }
    );
  } catch (err) {
    console.error('[invoicing] could not subscribe:', err);
    invoicesLoadError = err.message;
  }
}

export function destroy() {
  currentPage = 'list';
  if (invoicesUnsub) { try { invoicesUnsub(); } catch {} invoicesUnsub = null; }
}

function renderList() {
  const container = document.getElementById('view-invoicing');
  container.innerHTML = '';

  if (invoicesLoadError) {
    const banner = document.createElement('div');
    banner.style.cssText = 'padding:0.75rem 1rem;margin-bottom:0.75rem;background:rgba(220,38,38,0.08);color:var(--danger,#dc2626);border-radius:8px;font-size:0.85rem;';
    banner.innerHTML = `
      <strong>Can't load invoices:</strong> ${escapeHtml(invoicesLoadError)}
      <div style="margin-top:0.3rem;color:var(--gray-dark);font-size:0.78rem;">
        If the code is 'permission-denied', Firestore rules may not be published yet.
      </div>`;
    container.appendChild(banner);
  }

  const statusOptions = ['all', 'outstanding', 'draft', 'sent', 'paid', 'overdue', 'void', 'cancelled', 'refunded'];
  const hasActiveFilter = activeStatusFilter !== 'all' || activeDateFrom || activeDateTo;

  const topbar = document.createElement('div');
  topbar.className = 'view-topbar';
  topbar.style.cssText = 'flex-wrap:wrap;gap:0.5rem;';
  topbar.innerHTML = `
    <label style="display:flex;align-items:center;gap:0.25rem;font-size:0.85rem;color:var(--gray);">
      From <input type="date" id="invDateFrom" value="${escapeHtml(activeDateFrom)}" style="padding:0.35rem 0.5rem;border:1px solid var(--border);border-radius:6px;">
    </label>
    <label style="display:flex;align-items:center;gap:0.25rem;font-size:0.85rem;color:var(--gray);">
      To <input type="date" id="invDateTo" value="${escapeHtml(activeDateTo)}" style="padding:0.35rem 0.5rem;border:1px solid var(--border);border-radius:6px;">
    </label>
    ${hasActiveFilter ? '<button class="btn btn-ghost btn-sm" id="clearInvFilters">Clear</button>' : ''}
    ${canWrite() ? `<button class="btn btn-primary" id="addInvoiceBtn">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
      New Invoice
    </button>` : ''}
  `;
  container.appendChild(topbar);

  const tabs = document.createElement('div');
  tabs.style.cssText = 'display:flex;gap:0.25rem;margin-bottom:1rem;flex-wrap:wrap;';
  statusOptions.forEach(status => {
    const btn = document.createElement('button');
    btn.className = 'btn btn-ghost btn-sm' + (activeStatusFilter === status ? ' active' : '');
    if (activeStatusFilter === status) btn.style.cssText = 'background:var(--accent);color:white;';
    btn.textContent = status.charAt(0).toUpperCase() + status.slice(1);
    btn.addEventListener('click', () => { activeStatusFilter = status; renderList(); });
    tabs.appendChild(btn);
  });
  container.appendChild(tabs);

  const addBtn = topbar.querySelector('#addInvoiceBtn');
  if (addBtn) addBtn.addEventListener('click', gateWrite(() => openCreateForm()));

  topbar.querySelector('#invDateFrom').addEventListener('change', e => { activeDateFrom = e.target.value; renderList(); });
  topbar.querySelector('#invDateTo').addEventListener('change', e => { activeDateTo = e.target.value; renderList(); });
  const clearBtn = topbar.querySelector('#clearInvFilters');
  if (clearBtn) clearBtn.addEventListener('click', () => { activeStatusFilter = 'all'; activeDateFrom = ''; activeDateTo = ''; renderList(); });

  // Apply filters
  const fromMs = activeDateFrom ? new Date(activeDateFrom + 'T00:00:00').getTime() : null;
  const toMs = activeDateTo ? new Date(activeDateTo + 'T23:59:59').getTime() : null;
  const invTime = (i) => {
    if (i.createdAt && i.createdAt.toDate) return i.createdAt.toDate().getTime();
    return i.issueDate ? new Date(i.issueDate).getTime() : 0;
  };
  let filtered = invoices;
  if (activeStatusFilter === 'outstanding') {
    filtered = filtered.filter(i => ['draft', 'sent', 'overdue'].includes(i.status));
  } else if (activeStatusFilter !== 'all') {
    filtered = filtered.filter(i => (i.status || 'draft') === activeStatusFilter);
  }
  if (fromMs || toMs) {
    filtered = filtered.filter(i => {
      const t = invTime(i);
      if (!t) return false;
      if (fromMs && t < fromMs) return false;
      if (toMs && t > toMs) return false;
      return true;
    });
  }

  const wrapper = document.createElement('div');
  wrapper.className = 'view-content';

  if (filtered.length === 0) {
    wrapper.innerHTML = invoices.length === 0
      ? '<div class="empty-state"><div class="empty-title">No invoices yet</div><p class="empty-description">Create your first invoice to start billing clients.</p></div>'
      : '<div class="empty-state"><p class="empty-description">No invoices match your filters.</p></div>';
  } else {
    // Outstanding balance banner — click "Record Payment" to allocate across any open invoices.
    const outstandingTotal = filtered
      .filter(i => ['sent', 'overdue', 'partial', 'draft', 'issued'].includes(i.status))
      .reduce((s, i) => s + balanceOf(i), 0);

    const summary = document.createElement('div');
    summary.style.cssText = 'display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:0.85rem 1rem;background:var(--off-white,#F1F5F9);border-radius:10px;margin-bottom:0.75rem;flex-wrap:wrap;';
    summary.innerHTML = `
      <div>
        <div style="font-size:0.72rem;text-transform:uppercase;letter-spacing:0.05em;color:var(--gray-dark);">Outstanding</div>
        <div style="font-size:1.3rem;font-weight:600;font-variant-numeric:tabular-nums;">${formatCurrency(outstandingTotal)}</div>
        <div style="font-size:0.78rem;color:var(--gray);">${filtered.length} invoice${filtered.length === 1 ? '' : 's'} total</div>
      </div>
      ${outstandingTotal > 0 && canWrite() ? `<button class="btn btn-primary" id="recordPaymentAnyBtn">Record Payment</button>` : ''}
    `;
    wrapper.appendChild(summary);

    const recordAnyBtn = summary.querySelector('#recordPaymentAnyBtn');
    if (recordAnyBtn) {
      recordAnyBtn.addEventListener('click', async () => {
        const open = filtered.filter(i => ['sent', 'overdue', 'partial', 'draft', 'issued'].includes(i.status));
        const result = await openRecordPayment({ invoices: open });
        if (result?.recorded) render();
      });
    }

    const table = document.createElement('table');
    table.className = 'data-table';
    table.innerHTML = '<thead><tr><th>Invoice #</th><th>Client</th><th>Amount</th><th>Balance</th><th>Status</th><th>Date</th><th></th></tr></thead>';
    const tbody = document.createElement('tbody');

    filtered.forEach(inv => {
      const statusClass = inv.status === 'paid' ? 'badge-success'
                       : inv.status === 'partial' ? 'badge-info'
                       : inv.status === 'sent' ? 'badge-info'
                       : inv.status === 'overdue' ? 'badge-danger'
                       : 'badge-default';
      const bal = balanceOf(inv);
      const canRecord = canWrite() && bal > 0 && inv.status !== 'paid' && inv.type !== 'refund';
      const tr = document.createElement('tr');
      tr.className = 'clickable';
      tr.innerHTML = `
        <td style="font-weight:500;">${escapeHtml(inv.invoiceNumber || '-')}</td>
        <td>${escapeHtml(inv.clientName || '-')}</td>
        <td>${formatCurrency(inv.total || 0)}</td>
        <td>${bal > 0 ? formatCurrency(bal) : '<span style="color:var(--gray);">—</span>'}</td>
        <td><span class="badge ${statusClass}">${escapeHtml(inv.status || 'draft')}</span></td>
        <td>${formatDate(inv.issueDate || inv.createdAt)}</td>
        <td style="text-align:right;white-space:nowrap;">
          ${canRecord ? `<button class="btn btn-ghost btn-sm" data-record-invoice="${escapeHtml(inv.id)}">Record Payment</button>` : ''}
        </td>
      `;
      // Don't navigate if clicking the action button
      tr.addEventListener('click', (e) => {
        if (e.target.closest('[data-record-invoice]')) return;
        showDetail(inv);
      });
      tbody.appendChild(tr);
    });

    table.appendChild(tbody);
    wrapper.appendChild(table);

    wrapper.querySelectorAll('[data-record-invoice]').forEach(btn => {
      btn.addEventListener('click', async (e) => {
        e.stopPropagation();
        const inv = filtered.find(x => x.id === btn.dataset.recordInvoice);
        if (!inv) return;
        const result = await openRecordPayment({
          invoices: [inv],
          presetInvoiceId: inv.id,
          singleInvoiceMode: true,
          title: `Record Payment — ${inv.invoiceNumber || 'Invoice'}`,
        });
        if (result?.recorded) render();
      });
    });
  }

  function balanceOf(i) {
    const total = Math.abs(Number(i.total || i.amount || 0));
    const paid = Number(i.paidAmount || 0);
    return Math.max(0, total - paid);
  }

  container.appendChild(wrapper);
}

function openCreateForm() {
  currentPage = 'create';
  const container = document.getElementById('view-invoicing');
  container.innerHTML = '';

  const backBtn = document.createElement('button');
  backBtn.className = 'detail-back';
  backBtn.innerHTML = '&larr; Back';
  backBtn.addEventListener('click', () => { currentPage = 'list'; renderList(); });
  container.appendChild(backBtn);

  const invNum = `INV-${String(Date.now()).slice(-6)}`;

  const form = document.createElement('form');
  form.className = 'modal-form';
  form.style.maxWidth = '700px';
  form.innerHTML = `
    <h2 style="margin-bottom:1rem;">New Invoice</h2>
    <div class="modal-form-grid">
      <div class="modal-field"><label>Invoice #</label><input type="text" name="invoiceNumber" value="${invNum}" readonly style="background:var(--bg);"></div>
      <div class="modal-field"><label>Client Name *</label><input type="text" name="clientName" required></div>
    </div>
    <div class="modal-form-grid">
      <div class="modal-field"><label>Issue Date</label><input type="date" name="issueDate" value="${new Date().toISOString().split('T')[0]}"></div>
      <div class="modal-field"><label>Due Date</label><input type="date" name="dueDate" value="${new Date(Date.now() + 30*24*60*60*1000).toISOString().split('T')[0]}"></div>
    </div>

    <div class="modal-field"><label>Line Items</label></div>
    <table class="data-table" id="lineItemsTable" style="margin-bottom:0.5rem;">
      <thead><tr><th>Description</th><th style="width:80px;">Qty</th><th style="width:100px;">Rate</th><th style="width:100px;">Amount</th><th style="width:40px;"></th></tr></thead>
      <tbody id="lineItemsBody">
        <tr class="line-item-row">
          <td><input type="text" name="desc_0" placeholder="Description" style="width:100%;border:none;outline:none;"></td>
          <td><input type="number" name="qty_0" value="1" step="0.5" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
          <td><input type="number" name="rate_0" value="0" step="0.01" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
          <td class="line-amount" style="text-align:right;">$0.00</td>
          <td><button type="button" class="btn btn-ghost btn-sm remove-line" style="color:var(--danger);padding:0.2rem;">&times;</button></td>
        </tr>
      </tbody>
    </table>
    <button type="button" class="btn btn-ghost btn-sm" id="addLineBtn">+ Add Line</button>

    <div style="display:flex;justify-content:flex-end;margin-top:1rem;gap:1rem;align-items:center;">
      <span id="invoiceTotal" style="font-size:1.1rem;font-weight:600;">Total: $0.00</span>
    </div>

    <div class="modal-field" style="margin-top:1rem;"><label>Notes</label><textarea name="notes" rows="2"></textarea></div>
    <div style="display:flex;gap:0.5rem;margin-top:1rem;">
      <button type="submit" class="btn btn-primary">Create Invoice</button>
      <button type="button" class="btn btn-ghost" id="cancelCreate">Cancel</button>
    </div>
  `;

  let lineCount = 1;

  function recalcTotals() {
    let total = 0;
    form.querySelectorAll('.line-item-row').forEach((row, i) => {
      const qty = parseFloat(row.querySelector(`[name^="qty_"]`).value) || 0;
      const rate = parseFloat(row.querySelector(`[name^="rate_"]`).value) || 0;
      const amount = qty * rate;
      total += amount;
      row.querySelector('.line-amount').textContent = formatCurrency(amount);
    });
    form.querySelector('#invoiceTotal').textContent = `Total: ${formatCurrency(total)}`;
  }

  form.addEventListener('input', (e) => {
    if (e.target.name && (e.target.name.startsWith('qty_') || e.target.name.startsWith('rate_'))) recalcTotals();
  });

  form.querySelector('#addLineBtn').addEventListener('click', () => {
    const tbody = form.querySelector('#lineItemsBody');
    const tr = document.createElement('tr');
    tr.className = 'line-item-row';
    tr.innerHTML = `
      <td><input type="text" name="desc_${lineCount}" placeholder="Description" style="width:100%;border:none;outline:none;"></td>
      <td><input type="number" name="qty_${lineCount}" value="1" step="0.5" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td><input type="number" name="rate_${lineCount}" value="0" step="0.01" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td class="line-amount" style="text-align:right;">$0.00</td>
      <td><button type="button" class="btn btn-ghost btn-sm remove-line" style="color:var(--danger);padding:0.2rem;">&times;</button></td>
    `;
    tbody.appendChild(tr);
    lineCount++;
  });

  form.addEventListener('click', (e) => {
    if (e.target.classList.contains('remove-line')) {
      const row = e.target.closest('tr');
      if (form.querySelectorAll('.line-item-row').length > 1) { row.remove(); recalcTotals(); }
    }
  });

  form.querySelector('#cancelCreate').addEventListener('click', () => { currentPage = 'list'; renderList(); });

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const fd = new FormData(form);
    const lineItems = [];
    let total = 0;
    form.querySelectorAll('.line-item-row').forEach((row, i) => {
      const desc = row.querySelector(`[name^="desc_"]`).value.trim();
      const qty = parseFloat(row.querySelector(`[name^="qty_"]`).value) || 0;
      const rate = parseFloat(row.querySelector(`[name^="rate_"]`).value) || 0;
      const amount = qty * rate;
      if (desc) { lineItems.push({ description: desc, quantity: qty, rate, amount }); total += amount; }
    });

    try {
      await addDocument('invoices_crm', {
        invoiceNumber: fd.get('invoiceNumber'),
        clientName: fd.get('clientName').trim(),
        issueDate: fd.get('issueDate'),
        dueDate: fd.get('dueDate'),
        lineItems,
        subtotal: total,
        taxRate: 0,
        taxAmount: 0,
        total,
        status: 'draft',
        notes: fd.get('notes').trim()
      });
      currentPage = 'list';
      await render();
    } catch (err) {
      console.error('Create invoice failed:', err);
      alert('Failed to create invoice: ' + err.message);
    }
  });

  container.appendChild(form);
}

function openEditForm(inv) {
  currentPage = 'edit';
  const container = document.getElementById('view-invoicing');
  container.innerHTML = '';

  const backBtn = document.createElement('button');
  backBtn.className = 'detail-back';
  backBtn.innerHTML = '&larr; Back';
  backBtn.addEventListener('click', () => { showDetail(inv); });
  container.appendChild(backBtn);

  const form = document.createElement('form');
  form.className = 'modal-form';
  form.style.maxWidth = '700px';

  const existingLines = Array.isArray(inv.lineItems) ? inv.lineItems : [];
  const nonDiscountLines = existingLines.filter(l => !l.isDiscount);
  const discountLine = existingLines.find(l => l.isDiscount);
  const hasDiscount = !!discountLine || (inv.discountAmount || 0) > 0;

  form.innerHTML = `
    <h2 style="margin-bottom:1rem;">Edit Invoice ${escapeHtml(inv.invoiceNumber)}</h2>
    <div class="modal-form-grid">
      <div class="modal-field"><label>Invoice #</label><input type="text" name="invoiceNumber" value="${escapeHtml(inv.invoiceNumber || '')}" readonly style="background:var(--bg);"></div>
      <div class="modal-field"><label>Client Name *</label><input type="text" name="clientName" required value="${escapeHtml(inv.clientName || '')}"></div>
    </div>
    <div class="modal-form-grid">
      <div class="modal-field"><label>Issue Date</label><input type="date" name="issueDate" value="${escapeHtml(inv.issueDate || new Date().toISOString().split('T')[0])}"></div>
      <div class="modal-field"><label>Due Date</label><input type="date" name="dueDate" value="${escapeHtml(inv.dueDate || '')}"></div>
    </div>

    <div class="modal-field"><label>Line Items</label></div>
    <table class="data-table" id="lineItemsTable" style="margin-bottom:0.5rem;">
      <thead><tr><th>Description</th><th style="width:80px;">Qty</th><th style="width:100px;">Rate</th><th style="width:100px;">Amount</th><th style="width:40px;"></th></tr></thead>
      <tbody id="lineItemsBody">
        ${nonDiscountLines.map((li, i) => `
          <tr class="line-item-row">
            <td><input type="text" name="desc_${i}" value="${escapeHtml(li.description || '')}" style="width:100%;border:none;outline:none;"></td>
            <td><input type="number" name="qty_${i}" value="${li.quantity || 0}" step="0.5" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
            <td><input type="number" name="rate_${i}" value="${li.rate || 0}" step="0.01" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
            <td class="line-amount" style="text-align:right;">${formatCurrency(li.amount || 0)}</td>
            <td><button type="button" class="btn btn-ghost btn-sm remove-line" style="color:var(--danger);padding:0.2rem;">&times;</button></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
    <button type="button" class="btn btn-ghost btn-sm" id="addLineBtn">+ Add Line</button>

    <details style="margin-top:1rem;" ${hasDiscount ? 'open' : ''}>
      <summary style="cursor:pointer;font-weight:500;padding:0.25rem 0;">Discount</summary>
      <div class="modal-form-grid" style="padding-top:0.5rem;">
        <div class="modal-field">
          <label>Reason</label>
          <input type="text" name="discountReason" value="${escapeHtml(inv.discountReason || '')}" placeholder="e.g., Military">
        </div>
        <div class="modal-field">
          <label>Type</label>
          <select name="discountType">
            <option value="percent" ${inv.discountType === 'percent' ? 'selected' : ''}>% off</option>
            <option value="amount" ${inv.discountType === 'amount' ? 'selected' : ''}>$ off</option>
          </select>
        </div>
        <div class="modal-field">
          <label>Value</label>
          <input type="number" name="discountValue" min="0" step="0.01" value="${inv.discountValue || 0}">
        </div>
      </div>
    </details>

    <div class="modal-field" style="margin-top:1rem;max-width:180px;">
      <label>Tax Rate (%)</label>
      <input type="number" name="taxRate" min="0" max="100" step="0.001" value="${inv.taxRate || 0}">
    </div>

    <div style="display:flex;justify-content:flex-end;margin-top:1rem;gap:1rem;align-items:center;flex-wrap:wrap;">
      <span id="invoiceSubtotal" style="color:var(--gray);">Subtotal: ${formatCurrency(0)}</span>
      <span id="invoiceDiscount" style="color:#059669;">Discount: ${formatCurrency(0)}</span>
      <span id="invoiceTax" style="color:var(--gray);">Tax: ${formatCurrency(0)}</span>
      <span id="invoiceTotal" style="font-size:1.1rem;font-weight:600;">Total: ${formatCurrency(0)}</span>
    </div>

    <div class="modal-field" style="margin-top:1rem;"><label>Notes</label><textarea name="notes" rows="2">${escapeHtml(inv.notes || '')}</textarea></div>
    <div style="display:flex;gap:0.5rem;margin-top:1rem;">
      <button type="submit" class="btn btn-primary">Save Changes</button>
      <button type="button" class="btn btn-ghost" id="cancelEdit">Cancel</button>
    </div>
  `;

  let lineCount = nonDiscountLines.length || 1;
  if (nonDiscountLines.length === 0) {
    // Add one empty row
    const tbody = form.querySelector('#lineItemsBody');
    const tr = document.createElement('tr');
    tr.className = 'line-item-row';
    tr.innerHTML = `
      <td><input type="text" name="desc_0" placeholder="Description" style="width:100%;border:none;outline:none;"></td>
      <td><input type="number" name="qty_0" value="1" step="0.5" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td><input type="number" name="rate_0" value="0" step="0.01" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td class="line-amount" style="text-align:right;">$0.00</td>
      <td><button type="button" class="btn btn-ghost btn-sm remove-line" style="color:var(--danger);padding:0.2rem;">&times;</button></td>
    `;
    tbody.appendChild(tr);
  }

  function recalcTotals() {
    let subtotal = 0;
    form.querySelectorAll('.line-item-row').forEach((row) => {
      const qty = parseFloat(row.querySelector(`[name^="qty_"]`).value) || 0;
      const rate = parseFloat(row.querySelector(`[name^="rate_"]`).value) || 0;
      const amount = qty * rate;
      subtotal += amount;
      row.querySelector('.line-amount').textContent = formatCurrency(amount);
    });

    const dType = form.querySelector('[name="discountType"]').value;
    const dVal = parseFloat(form.querySelector('[name="discountValue"]').value) || 0;
    let discount = 0;
    if (dVal > 0) {
      if (dType === 'percent') discount = Math.round(subtotal * (Math.min(dVal, 100) / 100) * 100) / 100;
      else discount = Math.min(dVal, subtotal);
    }
    const afterDiscount = Math.max(0, subtotal - discount);
    const taxRate = parseFloat(form.querySelector('[name="taxRate"]').value) || 0;
    const tax = taxRate > 0 ? Math.round(afterDiscount * (taxRate / 100) * 100) / 100 : 0;
    const total = afterDiscount + tax;

    form.querySelector('#invoiceSubtotal').textContent = `Subtotal: ${formatCurrency(subtotal)}`;
    form.querySelector('#invoiceDiscount').textContent = `Discount: ${formatCurrency(discount)}`;
    form.querySelector('#invoiceDiscount').style.display = discount > 0 ? '' : 'none';
    form.querySelector('#invoiceTax').textContent = `Tax: ${formatCurrency(tax)}`;
    form.querySelector('#invoiceTax').style.display = tax > 0 ? '' : 'none';
    form.querySelector('#invoiceTotal').textContent = `Total: ${formatCurrency(total)}`;
  }

  form.addEventListener('input', (e) => {
    if (e.target.name && (e.target.name.startsWith('qty_') || e.target.name.startsWith('rate_') || e.target.name === 'discountValue' || e.target.name === 'discountType' || e.target.name === 'taxRate')) {
      recalcTotals();
    }
  });
  form.addEventListener('change', (e) => {
    if (e.target.name === 'discountType') recalcTotals();
  });

  form.querySelector('#addLineBtn').addEventListener('click', () => {
    const tbody = form.querySelector('#lineItemsBody');
    const tr = document.createElement('tr');
    tr.className = 'line-item-row';
    tr.innerHTML = `
      <td><input type="text" name="desc_${lineCount}" placeholder="Description" style="width:100%;border:none;outline:none;"></td>
      <td><input type="number" name="qty_${lineCount}" value="1" step="0.5" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td><input type="number" name="rate_${lineCount}" value="0" step="0.01" min="0" style="width:100%;border:none;outline:none;text-align:right;"></td>
      <td class="line-amount" style="text-align:right;">$0.00</td>
      <td><button type="button" class="btn btn-ghost btn-sm remove-line" style="color:var(--danger);padding:0.2rem;">&times;</button></td>
    `;
    tbody.appendChild(tr);
    lineCount++;
  });

  form.addEventListener('click', (e) => {
    if (e.target.classList.contains('remove-line')) {
      const row = e.target.closest('tr');
      if (form.querySelectorAll('.line-item-row').length > 1) { row.remove(); recalcTotals(); }
    }
  });

  form.querySelector('#cancelEdit').addEventListener('click', () => { showDetail(inv); });

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const fd = new FormData(form);
    const lineItems = [];
    let subtotal = 0;
    form.querySelectorAll('.line-item-row').forEach((row) => {
      const desc = row.querySelector(`[name^="desc_"]`).value.trim();
      const qty = parseFloat(row.querySelector(`[name^="qty_"]`).value) || 0;
      const rate = parseFloat(row.querySelector(`[name^="rate_"]`).value) || 0;
      const amount = qty * rate;
      if (desc) { lineItems.push({ description: desc, quantity: qty, rate, amount }); subtotal += amount; }
    });

    const dReason = fd.get('discountReason').trim();
    const dType = fd.get('discountType');
    const dVal = parseFloat(fd.get('discountValue')) || 0;
    let discountAmount = 0;
    if (dVal > 0 && dReason) {
      if (dType === 'percent') discountAmount = Math.round(subtotal * (Math.min(dVal, 100) / 100) * 100) / 100;
      else discountAmount = Math.min(dVal, subtotal);
      if (discountAmount > 0) {
        const label = dType === 'percent' ? `Discount — ${dReason} (${dVal}% off)` : `Discount — ${dReason}`;
        lineItems.push({ description: label, quantity: 1, rate: -discountAmount, amount: -discountAmount, isDiscount: true });
      }
    }
    const afterDiscount = Math.max(0, subtotal - discountAmount);
    const taxRate = parseFloat(fd.get('taxRate')) || 0;
    const taxAmount = taxRate > 0 ? Math.round(afterDiscount * (taxRate / 100) * 100) / 100 : 0;
    const total = afterDiscount + taxAmount;

    try {
      const patch = {
        clientName: fd.get('clientName').trim(),
        issueDate: fd.get('issueDate'),
        dueDate: fd.get('dueDate'),
        lineItems,
        subtotal,
        discountReason: dVal > 0 && dReason ? dReason : '',
        discountType: dVal > 0 && dReason ? dType : '',
        discountValue: dVal > 0 && dReason ? dVal : 0,
        discountAmount,
        taxRate,
        taxAmount,
        total,
        notes: fd.get('notes').trim()
      };
      await updateDocument('invoices_crm', inv.id, patch);
      Object.assign(inv, patch);
      showDetail(inv);
    } catch (err) {
      console.error('Update invoice failed:', err);
      alert('Failed to save: ' + err.message);
    }
  });

  container.appendChild(form);
  recalcTotals();
}

function showDetail(inv) {
  currentPage = 'detail';
  const container = document.getElementById('view-invoicing');
  container.innerHTML = '';

  const backBtn = document.createElement('button');
  backBtn.className = 'detail-back';
  backBtn.innerHTML = '&larr; Back';
  backBtn.addEventListener('click', () => { currentPage = 'list'; renderList(); });
  container.appendChild(backBtn);

  const statusClassMap = {
    paid: 'badge-success',
    sent: 'badge-info',
    overdue: 'badge-danger',
    void: 'badge-default',
    cancelled: 'badge-default',
    refunded: 'badge-warning',
    draft: 'badge-default'
  };
  const statusClass = statusClassMap[inv.status] || 'badge-default';

  const header = document.createElement('div');
  header.className = 'detail-header';
  header.innerHTML = `
    <div style="flex:1;">
      <div class="detail-name">${escapeHtml(inv.invoiceNumber)}</div>
      <div class="detail-subtitle">${escapeHtml(inv.clientName || '-')} &middot; <span class="badge ${statusClass}">${escapeHtml(inv.status || 'draft')}</span></div>
    </div>
    <div style="font-size:1.5rem;font-weight:600;font-family:var(--font-display);">${formatCurrency(inv.total || 0)}</div>
  `;
  container.appendChild(header);

  // Status change + lifecycle action buttons
  async function doStatusChange(newStatus, successMsg) {
    try {
      await updateDocument('invoices_crm', inv.id, { status: newStatus });
      inv.status = newStatus;
      showDetail(inv);
    } catch (err) {
      console.error('Status update failed:', err);
      alert('Failed to update status: ' + err.message);
    }
  }

  if (canWrite()) {
    const actions = document.createElement('div');
    actions.style.cssText = 'display:flex;gap:0.5rem;margin:1rem 0;flex-wrap:wrap;';

    const st = inv.status || 'draft';
    const addBtn = (label, cls, onClick, extraStyle = '') => {
      const b = document.createElement('button');
      b.className = `btn ${cls} btn-sm`;
      b.textContent = label;
      if (extraStyle) b.style.cssText = extraStyle;
      b.addEventListener('click', onClick);
      actions.appendChild(b);
    };

    if (st === 'draft' || st === 'sent') {
      addBtn('Edit', 'btn-ghost', gateWrite(() => openEditForm(inv)));
    }
    if (st === 'draft') {
      addBtn('Mark as Sent', 'btn-primary', gateWrite(() => doStatusChange('sent')));
    }
    if (st === 'draft' || st === 'sent' || st === 'overdue') {
      addBtn('Mark as Paid', 'btn-primary', gateWrite(() => doStatusChange('paid')), 'background:#059669;');
    }
    if (st === 'paid') {
      addBtn('Refund', 'btn-ghost', gateWrite(async () => {
        if (!confirm('Mark this invoice as refunded? This records that you returned the payment to the customer.')) return;
        await doStatusChange('refunded');
      }), 'color:#d97706;');
    }
    if (st === 'draft' || st === 'sent' || st === 'overdue') {
      addBtn('Cancel', 'btn-ghost', gateWrite(async () => {
        if (!confirm('Cancel this invoice? It will stay on record but be excluded from outstanding totals.')) return;
        await doStatusChange('cancelled');
      }), 'color:#d97706;');
    }
    if (st !== 'void' && st !== 'cancelled') {
      addBtn('Void', 'btn-ghost', gateWrite(async () => {
        const msg = st === 'paid'
          ? 'Void a PAID invoice? This is for accounting corrections only — usually you want Refund instead. Continue?'
          : 'Void this invoice? Use this for invoices created in error.';
        if (!confirm(msg)) return;
        await doStatusChange('void');
      }), 'color:var(--danger);');
    }
    if (st === 'draft' || st === 'void' || st === 'cancelled') {
      addBtn('Delete', 'btn-ghost', gateWrite(async () => {
        if (!confirm('Permanently delete this invoice? This cannot be undone.')) return;
        try {
          await deleteDocument('invoices_crm', inv.id);
          // If the invoice was linked to a ticket, clear the ticket's invoiceId
          // so the user can generate a replacement invoice from it.
          if (inv.ticketId) {
            try { await updateDocument('tickets', inv.ticketId, { invoiceId: null }); }
            catch (e) { console.warn('Failed to unlink invoice from ticket', e); }
          }
          currentPage = 'list';
          await render();
        } catch (err) { alert('Delete failed: ' + err.message); }
      }), 'color:var(--danger);');
    }

    if (actions.children.length > 0) container.appendChild(actions);
  }

  if (inv.ticketNumber) {
    const link = document.createElement('div');
    link.style.cssText = 'margin:0.5rem 0;font-size:0.85rem;color:var(--gray);';
    link.innerHTML = `From ticket <a href="#tickets" style="font-family:monospace;">${escapeHtml(inv.ticketNumber)}</a>`;
    container.appendChild(link);
  }

  // Line items
  if (inv.lineItems && inv.lineItems.length > 0) {
    const table = document.createElement('table');
    table.className = 'data-table';
    table.innerHTML = '<thead><tr><th>Description</th><th style="text-align:right;">Qty</th><th style="text-align:right;">Rate</th><th style="text-align:right;">Amount</th></tr></thead>';
    const tbody = document.createElement('tbody');
    inv.lineItems.forEach(li => {
      const tr = document.createElement('tr');
      const color = li.isDiscount ? 'color:#059669;' : '';
      tr.innerHTML = `
        <td style="${color}">${escapeHtml(li.description)}</td>
        <td style="text-align:right;${color}">${li.quantity}</td>
        <td style="text-align:right;${color}">${formatCurrency(li.rate)}</td>
        <td style="text-align:right;${color}">${formatCurrency(li.amount)}</td>
      `;
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    container.appendChild(table);

    const totals = document.createElement('div');
    totals.style.cssText = 'text-align:right;margin-top:1rem;font-size:0.95rem;';
    const hasDiscount = (inv.discountAmount || 0) > 0;
    const hasTax = (inv.taxAmount || 0) > 0;
    const rows = [];
    if (hasDiscount || hasTax) {
      rows.push(`<div>Subtotal: ${formatCurrency(inv.subtotal || 0)}</div>`);
    }
    if (hasDiscount) {
      const discountLabel = inv.discountType === 'percent'
        ? `Discount (${inv.discountValue}% ${escapeHtml(inv.discountReason || '')})`
        : `Discount (${escapeHtml(inv.discountReason || '')})`;
      rows.push(`<div style="color:#059669;">${discountLabel}: -${formatCurrency(inv.discountAmount || 0)}</div>`);
    }
    if (hasTax) {
      rows.push(`<div>Tax (${inv.taxRate}%): ${formatCurrency(inv.taxAmount || 0)}</div>`);
    }
    rows.push(`<div style="font-size:1.1rem;font-weight:600;margin-top:0.35rem;">Total: ${formatCurrency(inv.total || 0)}</div>`);
    totals.innerHTML = rows.join('');
    container.appendChild(totals);
  }

  if (inv.notes) {
    const notes = document.createElement('div');
    notes.style.cssText = 'margin-top:1.5rem;padding:1rem;background:var(--bg);border-radius:8px;font-size:0.9rem;';
    notes.innerHTML = `<strong>Notes:</strong> ${escapeHtml(inv.notes)}`;
    container.appendChild(notes);
  }
}

function escapeHtml(str) {
  if (!str) return '';
  const node = document.createElement('span');
  node.appendChild(document.createTextNode(str));
  return node.innerHTML;
}

function formatCurrency(amount) {
  if (amount == null || isNaN(amount)) return '$0.00';
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
}

function formatDate(timestamp) {
  if (!timestamp) return '\u2014';
  try {
    const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
    if (isNaN(date.getTime())) return '\u2014';
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch { return '\u2014'; }
}
